const SET_ASSETS = 'SET_ASSETS';
const ADD_ASSET = 'ADD_ASSET';
const UPDATE_ASSET = 'UPDATE_ASSET';
const DELETE_ASSET = 'DELETE_ASSET';

export { SET_ASSETS, ADD_ASSET, UPDATE_ASSET, DELETE_ASSET };
